### ISSUE TITLE
App failing to build after installing UXCam and following the instructions

### ISSUE THREAD

**Issue by onakatomi** [uxcam/uxcam-ios-swiftui#2]
I simply added the package dependency in XCode, and did the import statements & init lines as the docs say -- see screenshot below for confirmation.

The errors: 
- Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
- Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
- Linker command failed with exit code 1 (use -v to see invocation)

Here's a screenshot:

<img width="1024" alt="Screenshot 2024-04-17 at 3 27 41 pm" src="https://github.com/uxcam/uxcam-ios-swiftui/assets/145947039/393f9d1a-c122-440b-a072-09d0dc3d2d38">

**Comment by gabrieluxcam** [comment]
Hey @onakatomi  would it be possible to share a couple of details:

- Xcode version
- iOS Deployment target
- Have you added the SDK by SPM? Could you please confirm which url did you use if so? 


Thanks in advance

**Comment by harryblam** [comment]
I'm getting the same. 

Xcode version 15.2
Deployment target iOS 16
Added by SPM, url is https://github.com/uxcam/uxcam-ios-swiftui.git

Locking my version to 1.0.5 for workaround for now.

**Comment by onakatomi** [comment]
> Hey @onakatomi would it be possible to share a couple of details:
> 
> * Xcode version
> * iOS Deployment target
> * Have you added the SDK by SPM? Could you please confirm which url did you use if so?
> 
> Thanks in advance

Hey @gabrieluxcam, to answer your questions:
- 15.0.1
- iOS 16 & 17
- Yep, added via SPM in XCode: I used https://github.com/uxcam/uxcam-ios-swiftui

**Comment by DFDIEGOH** [comment]
Hi @harryblam and @onakatomi In order to install the latest version of the UXCam SDK, you will need to have XCode version 15.3. 

Can you upgrade your XCode version and check if you are able to integrate?

**Comment by gabrieluxcam** [comment]
Hello @harryblam @onakatomi We've released an updated SwiftUI SDK version 1.0.7 which allows versions lower than 15.3 of Xcode, could you give it a try and let us know? Thanks

**Comment by onakatomi** [comment]
@gabrieluxcam  @DFDIEGOH I updated to 15.3 and it worked.

**Comment by gabrieluxcam** [comment]
Thanks for the confirmation @onakatomi

**Comment by harryblam** [comment]
@gabrieluxcam  1.0.7 works on 15.2 now. Thanks for quick resolution.
